macos_machine:
  - x86_64-apple-darwin13.4.0
  - arm64-apple-darwin20.0.0
cross_target_platform:
  - osx-64
  - osx-arm64
gfortran_version:
  - 11.4.0
  - 12.3.0
zip_keys:
  - - cross_target_platform
    - macos_machine
MACOSX_DEPLOYMENT_TARGET:
  - 10.9
